# Change these first
owner: Bees-Hosting # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
#Start Core Services
  - name: Espace client
    url: https://my.beeshosting.eu.org
    __dangerous__disable_verify_peer: true
  - name: CPanel
    url: https://cpanel.beeshosting.eu.org
  - name: Serveur FTP
    url: ftpupload.net
    check: "tcp-ping"
    port: 21
  - name: Nameserver 1
    url: ns1.bs.cluster.ws
    check: "tcp-ping"
    port: 53
  - name: Nameserver 2
    url: ns2.bs.cluster.ws
    check: "tcp-ping"
    port: 53
    #Start Traige Services
  - name: Gestionnaire de fichiers en ligne
    url: https://filemanager.ai/new/
  - name: phpMyAdmin
    url: 185.27.134.10
    check: "tcp-ping"
  - name: Softaculous
    url: sv1.scriptinstall.rocks
    check: "tcp-ping"
    port: 2083
#Start Others
  - name: Site vitrine
    url: https://beeshosting.eu.org/
    __dangerous__disable_verify_peer: true
    #Start Third Party
  - name: API MyOwnFreeHost
    url: https://panel.myownfreehost.net/xml-api/
  - name: API GoGetSSL
    url: https://my.gogetssl.com/api/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.beeshosting.eu.org
  # baseUrl: /statuspage
  logoUrl: https://beeshosting.eu.org/assets/img/logo/favicon.png
  favicon: https://beeshosting.eu.org/assets/img/logo/favicon.png
  name: Statut - Bees Hosting
  theme: tabler
  introTitle: "Status des services de **Bees Hosting**"
  introMessage: Cette page d’état fournit des informations mises à jour sur le fonctionnement normal des systèmes de **Bees Hosting** et les incidents qui peuvent survenir.
  navbar:
    - title: Site
      href: https://beeshosting.eu.org
    - title: Espace client
      href: https://my.beeshosting.eu.org
  customBodyHtml: "<script src='https://beeshosting.eu.org/assets/cpanel/status.js'></script>" 

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: © Copyright 2022 Bees Hosting
  allSystemsOperational: Tout est opérationnel
